version: '3.1'
services:


  stats:
    build: ./stats
    #image:
    #container_name:
    ports:
      - "9090:9090"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres

  server:
    build: ./server
    ports:
      - "8080:8080"
    depends_on:
      - db
      - stats
    environment:
      - explore-with-me-stats_url=http://stats:9090
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres

  db:
    image: postgres:13.7-alpine
    volumes:
      - /var/lib/postgresql/data/
    #container_name:
    ports:
      - "6541:5432"
    environment:
      - DB_NAME=ewm
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=iamroot
      - DB_HOST=db
      - DB_PORT=5432
