drop table if exists users,category, events, participation, compilation, comp_events,
    items, bookings,requests, comments, items_requests;

CREATE TABLE if not exists users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(512) NOT NULL,
    CONSTRAINT pk_user PRIMARY KEY (id),
    CONSTRAINT UQ_USER_EMAIL UNIQUE (email)
    );

CREATE TABLE if not exists category(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    name VARCHAR NOT NULL UNIQUE
);

CREATE TABLE if not exists events(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    annotation VARCHAR NOT NULL,
    category_id BIGINT,
    created TIMESTAMP WITHOUT TIME ZONE,
    description VARCHAR,
    event_date TIMESTAMP WITHOUT TIME ZONE,
    initiator_id BIGINT,
    lat real,
    lon real,
    paid BOOLEAN,
    participant_limit BIGINT,
    published_on TIMESTAMP WITHOUT TIME ZONE,
    request_moderation BOOLEAN,
    title VARCHAR NOT NULL,
    state VARCHAR NOT NULL,
    views BIGINT,
    FOREIGN KEY (initiator_id) REFERENCES users (id),
    FOREIGN KEY (category_id) REFERENCES category (id)
);

CREATE TABLE if not exists participation(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    created TIMESTAMP WITHOUT TIME ZONE,
    event_id BIGINT,
    requester_id BIGINT,
    status VARCHAR,
    FOREIGN KEY (event_id) REFERENCES events(id)
    );

CREATE TABLE if not exists compilation(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    pinned BOOLEAN,
    title VARCHAR NOT NULL
);

CREATE TABLE if not exists comp_events(
    comp_id BIGINT,
    event_id BIGINT,
    FOREIGN KEY (event_id) REFERENCES events(id),
    FOREIGN KEY (comp_id) REFERENCES compilation(id)
);

