drop table if exists users,category, events, participation, compilation, comp_events,
    items, bookings,requests, comments, items_requests, comments;

CREATE TABLE if not exists users
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name  VARCHAR(50)                             NOT NULL,
    email VARCHAR(30)                             NOT NULL,
    CONSTRAINT pk_user PRIMARY KEY (id),
    CONSTRAINT UQ_USER_EMAIL UNIQUE (email)
);

CREATE TABLE if not exists category
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    name VARCHAR(30)                             NOT NULL UNIQUE
);

CREATE TABLE if not exists events
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    annotation         VARCHAR(1000)                           NOT NULL,
    category_id        BIGINT,
    created            TIMESTAMP WITHOUT TIME ZONE,
    description        VARCHAR(1000),
    event_date         TIMESTAMP WITHOUT TIME ZONE,
    initiator_id       BIGINT,
    lat                real,
    lon                real,
    paid               BOOLEAN,
    participant_limit  BIGINT,
    published_on       TIMESTAMP WITHOUT TIME ZONE,
    request_moderation BOOLEAN,
    title              VARCHAR(500)                            NOT NULL,
    state              VARCHAR(20)                             NOT NULL,
    views              BIGINT,
    FOREIGN KEY (initiator_id) REFERENCES users (id),
    FOREIGN KEY (category_id) REFERENCES category (id)
);

CREATE TABLE if not exists participation
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    created      TIMESTAMP WITHOUT TIME ZONE,
    event_id     BIGINT,
    requester_id BIGINT,
    status       VARCHAR(20),
    FOREIGN KEY (event_id) REFERENCES events (id)
);

CREATE TABLE if not exists compilation
(
    id     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    pinned BOOLEAN,
    title  VARCHAR(500)                            NOT NULL
);

CREATE TABLE if not exists comp_events
(
    comp_id  BIGINT,
    event_id BIGINT,
    FOREIGN KEY (event_id) REFERENCES events (id),
    FOREIGN KEY (comp_id) REFERENCES compilation (id)
);

CREATE TABLE if not exists comments
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    event_id    BIGINT,
    user_id     BIGINT,
    description varchar(1000),
    timestamp   TIMESTAMP WITHOUT TIME ZONE,
    FOREIGN KEY (event_id) REFERENCES events (id),
    FOREIGN KEY (user_id) REFERENCES users (id)
);

