drop table if exists stat;

CREATE TABLE if not exists stat (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    app VARCHAR(255) NOT NULL,
    uri VARCHAR(512) NOT NULL,
    ip VARCHAR(512) NOT NULL,
    timestamp TIMESTAMP WITHOUT TIME ZONE
    );
